pnpmfile: node_modules/.pnpm-config/@pnpm/better-defaults/pnpmfile.cjs
configDependencies:
  '@pnpm/better-defaults': 0.1.0+sha512-ikR/q6RSGqnn+6SSzmVEC+TgYhwb9OMdjkt0G5aNvZivE5SvsKwfK1lW1UDTLTpBqqVuv0duIz8ko0KdoSfcGw==
